# Generated by Django 2.0.3 on 2018-03-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180318_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='contact',
            field=models.TextField(null=True),
        ),
    ]
